### ISSUE TITLE
Add MB domains for intersections of slices and layers

### ISSUE THREAD

**Issue by dosumis** [FlyBase/drosophila-anatomy-developmental-ontology#192]

**Comment by dosumis** [comment]
Abbreviations  of terms to add (from filenames):

	a'1ap.nrrd
	a'1m.nrrd
	a'2ap.nrrd
	a'2m.nrrd
	a'3ap.nrrd
	a'3m.nrrd
	a1c.nrrd
	a1p.nrrd
	a1s.nrrd
	a2c.nrrd
	a2p.nrrd
	a2s.nrrd
	a3c.nrrd
	a3p.nrrd
	a3s.nrrd
	b'1ap.nrrd
	b'1m.nrrd
	b'2a.nrrd
	b'2m.nrrd
	b'2p.nrrd
	b1c.nrrd
	b1p.nrrd
	b1s.nrrd
	b2c.nrrd
	b2p.nrrd
	b2s.nrrd
	g1d.nrrd
	g1main.nrrd
	g2d.nrrd
	g2main.nrrd
	g3d.nrrd
	g3main.nrrd
	g4d.nrrd
	g4main.nrrd
	g5d.nrrd
	g5main.nrrd

a1c.nrrd  = alpha lobe slice 1, core layer
a1p.nrrd = alpha lobe slice 1, posterior layer
a1s.nrrd= alpha lobe slice 1, surface layer

etc

TODO: 
- [ ] Make general class for intersection slice with layer (?)
- [ ] Write design pattern doc
- [ ] iPython notebook to generate tsv
- [ ] Generate terms, test and merge.

**Comment by dosumis** [comment]
Sketch of design pattern (IDs to be filled in)

```yaml
pattern_name: MB_intersection_subdomain

classes:
    layer of mushroom body slice: 'FBbt:TBA'
    mushroom body slice: 'FBbt:...'
    mushroom body layer: 'FBbt:...'

relations:
    'part of': 'BFO:0000050'

vars:
     slice: 'mushroom body slice'
     layer: 'mushroom body layer'

name: 
    text: %s, %s
    vars: 
         - slice
         - layer

definition:
    text:  ' ... %s ... %s' 
    vars:
         - slice
         - layer

logical_axioms:
    - 
       axiom_type: SubClassOf
       text: ''
       vars: []
    - 
       axiom_type: SubClassOf
       text: 'part_of' some %s
       vars:
          - slice
  - 
       axiom_type: SubClassOf
       text: 'part_of' some %s
       vars:
          - layer
```

Potential additional logical axiom:

```yaml
   
    - 
       axiom_type: GCI
       text: ('part of' some %s) and ('part of' some %s) subClassOf ('part of' some Self)
       vars: 
         - slice
         - layer
```

But note - Self may not yet be implemented in DOSDP spec + may be hard to justify for anything so small - would anything ever be part of both.
